# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: what is wrong?
email: wenwei8268@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Website settings
title: "wenwei blog"
description: "wenwei's personal blog."
keywords: "wenwei,blog"
baseurl: "/"
url: "wenwei8268.github.io/jekyll-wenwei"
favicon: "static/img/favicon.ico?v=2"

author:
  name: 'wenwei zhou'
  email: 'wenwei8268@gmail.com'
  github: 'https://github.com/wenwei8268'
  linkedin: ''
  head_img: 'static/img/landing/wenwei.jpg'
  tag: ' Software, Reading,Travel,Mathematics and Sports'
  desc: >
           I am a java developer who focus on healthycare development; 



stylesheets:
  - url: "lib/css/bootstrap.min.css"
  - url: "lib/css/animate.min.css"
  - url: "static/css/style.min.css"

scripts:
  - url: "lib/js/jquery.min.js"
  - url: "lib/js/wow.min.js"
  - url: "lib/js/pace.min.js"
  - url: "lib/js/bootstrap.min.js"

sections:
  - id: "about"
    name: "About"
    tpl: "about.html"
  - id: "career"
    name: "Career"
    tpl: "timeline.html"
  - id: "projects"
    name: "Projects"
    tpl: "projects.html"

# google analytics
ga:
  id: UA-88257653-1

# Build settings
encoding: "utf-8"
